version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: myfrontend:latest
    ports:
      - "3000:3000" 

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: mybackend:latest
    ports:
      - "8081:8081"  
